// ─────────────────────────────────────────────
//  Shared car data + helpers
//  Import from both BrowseCars and the detail page
// ─────────────────────────────────────────────

export const tagColors = {
  Hypercar: {
    bg: "linear-gradient(135deg, #7f1d1d, #dc2626)",
    border: "#dc2626",
    text: "#ffffff",
  },
  Exotic: {
    bg: "linear-gradient(135deg, #b8963f, #f5d97b)",
    border: "#c9a84c",
    text: "#1a1a1a",
  },
  "Ultra Luxury": {
    bg: "linear-gradient(135deg, #4c1d95, #a855f7)",
    border: "#a855f7",
    text: "#ffffff",
  },
  Limited: {
    bg: "linear-gradient(135deg, #9a3412, #f97316)",
    border: "#f97316",
    text: "#ffffff",
  },
  Featured: {
    bg: "linear-gradient(135deg, #1e3a8a, #3b82f6)",
    border: "#3b82f6",
    text: "#ffffff",
  },
  Luxury: {
    bg: "linear-gradient(135deg, #134e4a, #14b8a6)",
    border: "#14b8a6",
    text: "#ffffff",
  },
  "Hot Deal": {
    bg: "linear-gradient(135deg, #a16207, #eab308)",
    border: "#eab308",
    text: "#1a1a1a",
  },
  EV: {
    bg: "linear-gradient(135deg, #14532d, #22c55e)",
    border: "#22c55e",
    text: "#ffffff",
  },
};

export const formatPrice = (p) => `$${p.toLocaleString()}`;

// Cars sorted: Hypercar > Exotic > Ultra Luxury > Limited > Featured > Luxury > Hot Deal > EV > null
export const allCars = [
  // ── HYPERCARS ──
  {
    id: 28,
    name: "Lamborghini Sián FKP",
    brand: "Lamborghini",
    type: "Hybrid",
    price: 3700000,
    year: 2024,
    hp: 819,
    image: "/comp/images/lamborgini-sian.jfif",
    tag: "Hypercar",
    description:
      "The Lamborghini Sián FKP 37 is a limited-production hybrid supercar — one of the most exclusive Lamborghinis ever built. Its naturally aspirated V12 pairs with a supercapacitor hybrid system for instantaneous torque response.",
    specs: {
      topSpeed: "220 mph",
      acceleration: "2.8s 0–60",
      engine: "6.5L V12 Hybrid",
      drivetrain: "AWD",
    },
  },
  {
    id: 26,
    name: "Lamborghini Aventador",
    brand: "Lamborghini",
    type: "Coupe",
    price: 450000,
    year: 2024,
    hp: 769,
    image: "/comp/images/lamborgini-1.jfif",
    tag: "Hypercar",
    description:
      "The Aventador LP 780-4 Ultimae is the final evolution of the iconic V12 Aventador lineage — raw, visceral, and uncompromising. A naturally aspirated masterpiece before electrification changes everything.",
    specs: {
      topSpeed: "221 mph",
      acceleration: "2.8s 0–60",
      engine: "6.5L V12",
      drivetrain: "AWD",
    },
  },
  {
    id: 15,
    name: "Ferrari SF90 Stradale",
    brand: "Ferrari",
    type: "Hybrid",
    price: 580000,
    year: 2024,
    hp: 986,
    image: "/comp/images/ferreri-2.jfif",
    tag: "Hypercar",
    description:
      "Ferrari's most powerful road car ever. The SF90 Stradale combines a twin-turbocharged V8 with three electric motors for a staggering 986 hp, capable of a 0–60 in 2.5 seconds.",
    specs: {
      topSpeed: "211 mph",
      acceleration: "2.5s 0–60",
      engine: "4.0L TT V8 + 3 Motors",
      drivetrain: "AWD",
    },
  },

  // ── EXOTIC ──
  {
    id: 27,
    name: "Lamborghini Huracán STO",
    brand: "Lamborghini",
    type: "Coupe",
    price: 330000,
    year: 2024,
    hp: 630,
    image: "/comp/images/lamborgini-2.jfif",
    tag: "Exotic",
    description:
      "The Huracán STO (Super Trofeo Omologata) brings motorsport DNA directly to the road. Aerodynamic bodywork, racing-derived suspension, and a screaming naturally aspirated V10 make this the most track-focused Lamborghini road car.",
    specs: {
      topSpeed: "193 mph",
      acceleration: "3.0s 0–60",
      engine: "5.2L NA V10",
      drivetrain: "RWD",
    },
  },
  {
    id: 22,
    name: "Lamborghini Huracán EVO",
    brand: "Lamborghini",
    type: "Coupe",
    price: 250000,
    year: 2024,
    hp: 640,
    image: "/comp/images/lamborghini-huracan.jfif",
    tag: "Exotic",
    description:
      "The Huracán EVO represents the peak of naturally aspirated engineering. With Lamborghini Dinamica Veicolo Integrata (LDVI), every drive adapts in real time to deliver breathtaking performance.",
    specs: {
      topSpeed: "202 mph",
      acceleration: "2.9s 0–60",
      engine: "5.2L NA V10",
      drivetrain: "AWD",
    },
  },
  {
    id: 14,
    name: "Ferrari F8 Tributo",
    brand: "Ferrari",
    type: "Coupe",
    price: 310000,
    year: 2024,
    hp: 710,
    image: "/comp/images/ferreri-1.jfif",
    tag: "Exotic",
    description:
      "A tribute to the most powerful V8 in Ferrari history. The F8 Tributo inherits the twin-turbo V8 from the 488 Pista and wraps it in a stunning body engineered for aerodynamic perfection.",
    specs: {
      topSpeed: "211 mph",
      acceleration: "2.9s 0–60",
      engine: "3.9L TT V8",
      drivetrain: "RWD",
    },
  },
  {
    id: 13,
    name: "Ferrari Roma",
    brand: "Ferrari",
    type: "Coupe",
    price: 280000,
    year: 2024,
    hp: 612,
    image: "/comp/images/Ferrari.jfif",
    tag: "Exotic",
    description:
      "The Ferrari Roma channels la dolce vita into a modern grand tourer. Elegant 2+ coupe styling meets blistering performance — a Ferrari you can drive every day without sacrificing anything.",
    specs: {
      topSpeed: "199 mph",
      acceleration: "3.4s 0–60",
      engine: "3.9L TT V8",
      drivetrain: "RWD",
    },
  },
  {
    id: 29,
    name: "McLaren 720S",
    brand: "McLaren",
    type: "Coupe",
    price: 310000,
    year: 2024,
    hp: 710,
    image: "/comp/images/meclaran-1.jfif",
    tag: "Exotic",
    description:
      "The McLaren 720S is a technological tour de force. Its carbon fibre MonoCell II chassis, twin-turbo V8, and radical aerodynamics make it one of the most capable supercars money can buy.",
    specs: {
      topSpeed: "212 mph",
      acceleration: "2.8s 0–60",
      engine: "4.0L TT V8",
      drivetrain: "RWD",
    },
  },
  {
    id: 1,
    name: "Aston Martin DB12",
    brand: "Aston Martin",
    type: "Coupe",
    price: 245000,
    year: 2024,
    hp: 671,
    image: "/comp/images/astan-martain-1.jfif",
    tag: "Exotic",
    description:
      "The DB12 is Aston Martin's Super Tourer — a new class of car defined by blistering performance and ravishing design. The hand-crafted interior, AMG-sourced twin-turbo V8, and magnetic ride control deliver a drive unlike any other.",
    specs: {
      topSpeed: "202 mph",
      acceleration: "3.5s 0–60",
      engine: "4.0L TT V8",
      drivetrain: "RWD",
    },
  },

  // ── ULTRA LUXURY ──
  {
    id: 37,
    name: "Rolls-Royce Cullinan",
    brand: "Rolls-Royce",
    type: "SUV",
    price: 430000,
    year: 2024,
    hp: 563,
    image: "/comp/images/rolls-royce-1.jfif",
    tag: "Ultra Luxury",
    description:
      "The Cullinan is the world's most luxurious SUV. Named after the largest diamond ever discovered, it offers an effortless journey through any terrain wrapped in the finest leathers, woods, and metals Rolls-Royce can source.",
    specs: {
      topSpeed: "155 mph",
      acceleration: "5.2s 0–60",
      engine: "6.75L Twin-Turbo V12",
      drivetrain: "AWD",
    },
  },
  {
    id: 36,
    name: "Rolls-Royce Ghost",
    brand: "Rolls-Royce",
    type: "Sedan",
    price: 380000,
    year: 2024,
    hp: 563,
    image: "/comp/images/rolls-royce.jfif",
    tag: "Ultra Luxury",
    description:
      "The Ghost is Rolls-Royce's most technologically advanced car. With an aluminium spaceframe architecture, Planar Suspension System, and over 100kg of sound insulation, it achieves near-silence at any speed.",
    specs: {
      topSpeed: "155 mph",
      acceleration: "4.8s 0–60",
      engine: "6.75L Twin-Turbo V12",
      drivetrain: "AWD",
    },
  },
  {
    id: 38,
    name: "Rolls-Royce Spectre",
    brand: "Rolls-Royce",
    type: "Electric",
    price: 420000,
    year: 2024,
    hp: 577,
    image: "/comp/images/rolls-royce-2.jfif",
    tag: "Ultra Luxury",
    description:
      "The Spectre is the world's first ultra-luxury electric super coupé. Effortlessly powerful, whisper-quiet, and breathtakingly beautiful — the Spectre redefines what electric mobility can mean.",
    specs: {
      topSpeed: "155 mph",
      acceleration: "4.5s 0–60",
      engine: "Dual Electric Motors",
      drivetrain: "AWD",
    },
  },

  // ── LIMITED ──
  {
    id: 16,
    name: "Nissan GT-R Nismo",
    brand: "Nissan",
    type: "Coupe",
    price: 215000,
    year: 2024,
    hp: 600,
    image: "/comp/images/GT-R.jfif",
    tag: "Limited",
    description:
      "The GT-R NISMO represents the pinnacle of Nissan performance engineering. Hand-assembled by Nismo technicians, each engine is carefully prepared to extract maximum power from the twin-turbo V6.",
    specs: {
      topSpeed: "196 mph",
      acceleration: "2.5s 0–60",
      engine: "3.8L Twin-Turbo V6",
      drivetrain: "AWD",
    },
  },
  {
    id: 11,
    name: "BMW M4 CSL",
    brand: "BMW",
    type: "Coupe",
    price: 140000,
    year: 2024,
    hp: 543,
    image: "/comp/images/bmw-m4.jfif",
    tag: "Limited",
    description:
      "Only 1,000 units worldwide. The M4 CSL (Coupé Sport Lightweight) strips 108 lbs from the standard M4 while adding 40 hp. Carbon fibre everywhere. No back seats. Pure driver's focus.",
    specs: {
      topSpeed: "191 mph",
      acceleration: "3.6s 0–60",
      engine: "3.0L TT Inline-6",
      drivetrain: "RWD",
    },
  },
  {
    id: 24,
    name: "Lamborghini Urus Performante",
    brand: "Lamborghini",
    type: "SUV",
    price: 270000,
    year: 2024,
    hp: 657,
    image: "/comp/images/Lamborghini-Urus-3.jfif",
    tag: "Limited",
    description:
      "The Urus Performante is the sharpest, fastest SUV Lamborghini has ever made. Weight reduction, recalibrated suspension, and 657 hp make it a track tool that happens to have four doors.",
    specs: {
      topSpeed: "193 mph",
      acceleration: "3.3s 0–60",
      engine: "4.0L Twin-Turbo V8",
      drivetrain: "AWD",
    },
  },

  // ── FEATURED ──
  {
    id: 33,
    name: "Porsche 911 Carrera S",
    brand: "Porsche",
    type: "Coupe",
    price: 135000,
    year: 2024,
    hp: 443,
    image: "/comp/images/porsche-911.jfif",
    tag: "Featured",
    description:
      "The Porsche 911 is the benchmark by which all sports cars are judged. The Carrera S adds a larger twin-turbo flat-six for an even more thrilling experience, while retaining the 911's legendary everyday usability.",
    specs: {
      topSpeed: "191 mph",
      acceleration: "3.5s 0–60",
      engine: "3.0L Twin-Turbo Flat-6",
      drivetrain: "RWD",
    },
  },
  {
    id: 6,
    name: "Bentley Continental GT",
    brand: "Bentley",
    type: "Coupe",
    price: 245000,
    year: 2024,
    hp: 659,
    image: "/comp/images/bentlay-2.jfif",
    tag: "Featured",
    description:
      "The Continental GT is the definitive grand tourer. Hand-stitched leather, polished wood veneers, and a 6.0L W12 biturbo deliver effortless refinement at any speed — on any road in the world.",
    specs: {
      topSpeed: "208 mph",
      acceleration: "3.6s 0–60",
      engine: "6.0L W12 Biturbo",
      drivetrain: "AWD",
    },
  },
  {
    id: 17,
    name: "Mercedes-Benz G63 AMG",
    brand: "Mercedes-Benz",
    type: "SUV",
    price: 185000,
    year: 2024,
    hp: 577,
    image: "/comp/images/G-wagon.jfif",
    tag: "Featured",
    description:
      "The G63 AMG is a cultural icon. Its square-shouldered silhouette has remained iconic for four decades — now underpinned by a 4.0L biturbo V8 and AMG Performance 4MATIC for legendary off-road and on-road capability.",
    specs: {
      topSpeed: "149 mph",
      acceleration: "4.5s 0–60",
      engine: "4.0L TT V8",
      drivetrain: "AWD",
    },
  },
  {
    id: 32,
    name: "Porsche 718 Cayman GT4",
    brand: "Porsche",
    type: "Coupe",
    price: 105000,
    year: 2024,
    hp: 414,
    image: "/comp/images/porsche-2.jfif",
    tag: "Featured",
    description:
      "The 718 Cayman GT4 is the purest Porsche you can buy below the 911. A naturally aspirated flat-six lifted from the 911, rear-wheel drive only, and an available PDK — this is the driver's car.",
    specs: {
      topSpeed: "188 mph",
      acceleration: "4.4s 0–60",
      engine: "4.0L NA Flat-6",
      drivetrain: "RWD",
    },
  },

  // ── LUXURY ──
  {
    id: 5,
    name: "Bentley Flying Spur",
    brand: "Bentley",
    type: "Sedan",
    price: 220000,
    year: 2024,
    hp: 626,
    image: "/comp/images/bentaly-1.jfif",
    tag: "Luxury",
    description:
      "The Flying Spur is Bentley's performance saloon — combining the luxury of the Mulsanne with the power of the Continental GT. All-wheel steering, adaptive air suspension, and a W12 biturbo create the ultimate four-door experience.",
    specs: {
      topSpeed: "207 mph",
      acceleration: "3.8s 0–60",
      engine: "6.0L W12 Biturbo",
      drivetrain: "AWD",
    },
  },
  {
    id: 20,
    name: "Mercedes-Benz S-Class",
    brand: "Mercedes-Benz",
    type: "Sedan",
    price: 115000,
    year: 2024,
    hp: 496,
    image: "/comp/images/mercdees-sclass.jfif",
    tag: "Luxury",
    description:
      "The Mercedes-Benz S-Class is the benchmark of automotive luxury. Every technology debuted here first — from airbags to active suspension. The W223 generation raises the bar again with a rear-axle steering system and MBUX Hyperscreen.",
    specs: {
      topSpeed: "155 mph",
      acceleration: "4.4s 0–60",
      engine: "3.0L I6 + EQ Boost",
      drivetrain: "AWD",
    },
  },
  {
    id: 34,
    name: "Range Rover Autobiography",
    brand: "Land Rover",
    type: "SUV",
    price: 195000,
    year: 2024,
    hp: 523,
    image: "/comp/images/Range Rover.jfif",
    tag: "Luxury",
    description:
      "The Range Rover Autobiography is the pinnacle of luxury SUVs. Semi-aniline leather, executive rear seating, and Terrain Response 2 make it equally at home crossing a desert or arriving at a black-tie event.",
    specs: {
      topSpeed: "155 mph",
      acceleration: "5.1s 0–60",
      engine: "4.4L Twin-Turbo V8",
      drivetrain: "AWD",
    },
  },

  // ── HOT DEAL ──
  {
    id: 2,
    name: "Audi RS7 Sportback",
    brand: "Audi",
    type: "Sedan",
    price: 120000,
    year: 2024,
    hp: 591,
    image: "/comp/images/Audi-1.jfif",
    tag: "Hot Deal",
    description:
      "The RS7 Sportback is Audi's four-door supercar. A 4.0L biturbo V8 with mild-hybrid technology, quattro AWD, and a fastback body that turns heads everywhere it goes — all while seating five in comfort.",
    specs: {
      topSpeed: "190 mph",
      acceleration: "3.6s 0–60",
      engine: "4.0L TT V8 MHEV",
      drivetrain: "AWD",
    },
  },
  {
    id: 8,
    name: "BMW M5",
    brand: "BMW",
    type: "Sedan",
    price: 108000,
    year: 2024,
    hp: 617,
    image: "/comp/images/bmw-1.jfif",
    tag: "Hot Deal",
    description:
      "The BMW M5 is the world's benchmark super saloon. The F90 generation added xDrive AWD for the first time, giving it all-weather capability without sacrificing its legendary rear-drive character when you want it.",
    specs: {
      topSpeed: "190 mph",
      acceleration: "3.2s 0–60",
      engine: "4.4L Twin-Turbo V8",
      drivetrain: "AWD",
    },
  },
  {
    id: 10,
    name: "BMW M3 Competition",
    brand: "BMW",
    type: "Sedan",
    price: 76000,
    year: 2024,
    hp: 503,
    image: "/comp/images/bmw-m3.jfif",
    tag: "Hot Deal",
    description:
      "The M3 Competition is BMW's most focused sports saloon. 503 hp, a 6-speed manual option, and perfectly balanced chassis make every journey memorable — whether commuting or attacking a track day.",
    specs: {
      topSpeed: "180 mph",
      acceleration: "3.8s 0–60",
      engine: "3.0L Twin-Turbo I6",
      drivetrain: "RWD/AWD",
    },
  },
  {
    id: 21,
    name: "Mercedes-AMG GT 63",
    brand: "Mercedes-Benz",
    type: "Coupe",
    price: 165000,
    year: 2024,
    hp: 630,
    image: "/comp/images/mercedes-2.jfif",
    tag: "Hot Deal",
    description:
      "The AMG GT 63 S 4-Door Coupé blends stunning proportions with breathtaking performance. A handcrafted AMG 4.0L biturbo V8 and active rear-axle steering create a car that is as beautiful as it is fast.",
    specs: {
      topSpeed: "196 mph",
      acceleration: "3.1s 0–60",
      engine: "4.0L TT V8",
      drivetrain: "AWD",
    },
  },
  {
    id: 35,
    name: "Range Rover Sport SVR",
    brand: "Land Rover",
    type: "SUV",
    price: 145000,
    year: 2024,
    hp: 575,
    image: "/comp/images/rangerover-1.jfif",
    tag: "Hot Deal",
    description:
      "The Range Rover Sport SVR is the fastest and most powerful Land Rover ever built. A supercharged 5.0L V8, active exhaust, and carbon ceramic brakes make it feel as at home on a racetrack as on a muddy country lane.",
    specs: {
      topSpeed: "176 mph",
      acceleration: "4.3s 0–60",
      engine: "5.0L Supercharged V8",
      drivetrain: "AWD",
    },
  },

  // ── EV ──
  {
    id: 40,
    name: "Tesla Model S Plaid",
    brand: "Tesla",
    type: "Electric",
    price: 95000,
    year: 2024,
    hp: 1020,
    image: "/comp/images/tesla-model-s.jfif",
    tag: "EV",
    description:
      "The Tesla Model S Plaid is the fastest accelerating production car ever made. Three motors, a tri-motor powertrain, and 1,020 hp deliver a 0–60 in under 2 seconds — while carrying five adults in comfort.",
    specs: {
      topSpeed: "200 mph",
      acceleration: "1.99s 0–60",
      engine: "Tri-Motor Electric",
      drivetrain: "AWD",
    },
  },
  {
    id: 31,
    name: "Porsche Taycan Turbo S",
    brand: "Porsche",
    type: "Electric",
    price: 185000,
    year: 2024,
    hp: 750,
    image: "/comp/images/porsche-1.jfif",
    tag: "EV",
    description:
      "The Taycan Turbo S proves Porsche's performance DNA extends seamlessly into the electric age. 800-volt architecture for ultra-fast charging, two permanent-magnet motors, and a 0–60 in 2.6 seconds.",
    specs: {
      topSpeed: "161 mph",
      acceleration: "2.6s 0–60",
      engine: "Dual Motor Electric 800V",
      drivetrain: "AWD",
    },
  },
  {
    id: 4,
    name: "Audi RS e-tron GT",
    brand: "Audi",
    type: "Electric",
    price: 142000,
    year: 2024,
    hp: 637,
    image: "/comp/images/audi-3.jfif",
    tag: "EV",
    description:
      "Sharing its platform with the Taycan, the RS e-tron GT is Audi's most beautiful car in decades. The sweeping gran turismo body, quattro AWD, and 800V fast charging combine technology with stunning aesthetics.",
    specs: {
      topSpeed: "155 mph",
      acceleration: "3.1s 0–60",
      engine: "Dual Motor Electric 800V",
      drivetrain: "AWD",
    },
  },

  // ── REST ──
  {
    id: 3,
    name: "Audi R8 V10",
    brand: "Audi",
    type: "Coupe",
    price: 165000,
    year: 2024,
    hp: 602,
    image: "/comp/images/audi-2.jfif",
    tag: null,
    description:
      "The Audi R8 is the everyday supercar perfected. A naturally aspirated 5.2L V10 revving to 8,250 rpm, quattro AWD, and a mid-engine layout create a supercar experience that never intimidates.",
    specs: {
      topSpeed: "205 mph",
      acceleration: "3.2s 0–60",
      engine: "5.2L NA V10",
      drivetrain: "AWD",
    },
  },
  {
    id: 7,
    name: "BMW M4 Competition",
    brand: "BMW",
    type: "Coupe",
    price: 85000,
    year: 2024,
    hp: 503,
    image: "/comp/images/bg-bmw.jfif",
    tag: null,
    description:
      "The M4 Competition is the ultimate expression of BMW's performance philosophy. With 503 hp, an 8-speed M Steptronic transmission, and optional M xDrive, it excels from mountain roads to the Nürburgring.",
    specs: {
      topSpeed: "180 mph",
      acceleration: "3.8s 0–60",
      engine: "3.0L Twin-Turbo I6",
      drivetrain: "RWD/AWD",
    },
  },
  {
    id: 9,
    name: "BMW 7 Series",
    brand: "BMW",
    type: "Sedan",
    price: 95000,
    year: 2024,
    hp: 536,
    image: "/comp/images/bmw-2.jfif",
    tag: null,
    description:
      "The BMW 7 Series redefines what a luxury saloon can be. The G70 generation introduces a 31.3-inch Theatre Screen in the rear, executive lounge seating, and a suite of BMW Individual customisation options.",
    specs: {
      topSpeed: "155 mph",
      acceleration: "4.1s 0–60",
      engine: "4.4L Twin-Turbo V8",
      drivetrain: "AWD",
    },
  },
  {
    id: 12,
    name: "BMW M4 Gran Coupe",
    brand: "BMW",
    type: "Coupe",
    price: 92000,
    year: 2024,
    hp: 503,
    image: "/comp/images/bmw-m4-1.jfif",
    tag: null,
    description:
      "The M4 Competition Gran Coupé delivers M performance without compromise. Four doors and a practical rear hatch meet 503 hp and xDrive for a car that genuinely has no limits — from school run to supercar slayer.",
    specs: {
      topSpeed: "180 mph",
      acceleration: "3.8s 0–60",
      engine: "3.0L Twin-Turbo I6",
      drivetrain: "AWD",
    },
  },
  {
    id: 18,
    name: "Mercedes-Benz G-Class",
    brand: "Mercedes-Benz",
    type: "SUV",
    price: 165000,
    year: 2024,
    hp: 416,
    image: "/comp/images/g-wagon-1.jfif",
    tag: null,
    description:
      "The G-Class is a legend that has outlasted every trend. Its three locking differentials, portal axles, and ladder frame make it genuinely capable off-road, while the AMG Line interior delivers luxury no one expected.",
    specs: {
      topSpeed: "130 mph",
      acceleration: "5.6s 0–60",
      engine: "3.0L I6 Turbo",
      drivetrain: "AWD",
    },
  },
  {
    id: 19,
    name: "Mercedes-AMG C63 S",
    brand: "Mercedes-Benz",
    type: "Sedan",
    price: 85000,
    year: 2024,
    hp: 671,
    image: "/comp/images/mercdees-1.jfif",
    tag: null,
    description:
      "The all-new C63 S E Performance is a dramatic reinvention. A 2.0L four-cylinder paired with a 204 hp rear-axle electric motor produces a combined 671 hp — more than the old V8, with instant electric torque layered on top.",
    specs: {
      topSpeed: "174 mph",
      acceleration: "3.4s 0–60",
      engine: "2.0L Turbo + Electric Motor",
      drivetrain: "AWD",
    },
  },
  {
    id: 23,
    name: "Lamborghini Urus S",
    brand: "Lamborghini",
    type: "SUV",
    price: 240000,
    year: 2024,
    hp: 666,
    image: "/comp/images/Lamborghini-Urus-2.jfif",
    tag: null,
    description:
      "The Urus S is the world's first Super Sport Utility Vehicle. A 4.0L twin-turbo V8, 666 hp, and Lamborghini's four-wheel steering create an SUV that laps the Nürburgring faster than most sports cars.",
    specs: {
      topSpeed: "190 mph",
      acceleration: "3.5s 0–60",
      engine: "4.0L Twin-Turbo V8",
      drivetrain: "AWD",
    },
  },
  {
    id: 25,
    name: "Lamborghini Urus Pearl",
    brand: "Lamborghini",
    type: "SUV",
    price: 260000,
    year: 2024,
    hp: 666,
    image: "/comp/images/Lamborghini-Urus-4.jfif",
    tag: null,
    description:
      "The Urus Pearl Capsule is a special series celebrating Lamborghini's bold design language. Contrasting roof, mirror caps, and interior accents in pearl colours make each one uniquely personal.",
    specs: {
      topSpeed: "190 mph",
      acceleration: "3.5s 0–60",
      engine: "4.0L Twin-Turbo V8",
      drivetrain: "AWD",
    },
  },
  {
    id: 30,
    name: "Nissan GT-R Premium",
    brand: "Nissan",
    type: "Coupe",
    price: 115000,
    year: 2024,
    hp: 565,
    image: "/comp/images/nissan-bg.jfif",
    tag: null,
    description:
      "Godzilla lives on. The GT-R Premium's hand-assembled VR38DETT twin-turbo V6 and ATTESA E-TS AWD system make it one of the most capable performance bargains in the world.",
    specs: {
      topSpeed: "196 mph",
      acceleration: "2.7s 0–60",
      engine: "3.8L Twin-Turbo V6",
      drivetrain: "AWD",
    },
  },
  {
    id: 39,
    name: "Land Rover Defender V8",
    brand: "Land Rover",
    type: "SUV",
    price: 115000,
    year: 2024,
    hp: 518,
    image: "/comp/images/rover range defender.jfif",
    tag: null,
    description:
      "The Defender V8 is the most powerful Defender ever made. A supercharged 5.0L V8, Configurable Terrain Response, and Wade sensing create an unstoppable off-roader that doesn't look like one.",
    specs: {
      topSpeed: "149 mph",
      acceleration: "4.9s 0–60",
      engine: "5.0L Supercharged V8",
      drivetrain: "AWD",
    },
  },
];